let sb=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY), list=[], editing=null;
document.addEventListener("DOMContentLoaded",async()=>{bind();const {data:{session}}=await sb.auth.getSession();if(session)showDash();});
function bind(){login.onclick=doLogin;logout.onclick=()=>sb.auth.signOut().then(()=>location.reload());type.onchange=()=>episodeArea.classList.toggle("hidden",type.value!=="series");form.onsubmit=save;q.oninput=()=>render(q.value);addEpisode.onclick=()=>episodeRow();cancel.onclick=reset;sb.auth.onAuthStateChange((_e,s)=>{if(s)showDash()})}
async function doLogin(e){e.preventDefault();loginMsg.textContent="";const {error}=await sb.auth.signInWithPassword({email:email.value,password:password.value});if(error)loginMsg.textContent=error.message}
async function showDash(){loginPanel.classList.add("hidden");dashboard.classList.remove("hidden");await refresh()}
async function refresh(){const r=await sb.from("contents").select("*").order("created_at",{ascending:false});if(r.error){toast(r.error.message);return}list=r.data||[];stats.innerHTML=`<div class="stat"><b>${list.length}</b><small>المحتوى</small></div><div class="stat"><b>${list.filter(x=>x.type==="movie").length}</b><small>الأفلام</small></div><div class="stat"><b>${list.filter(x=>x.type==="series").length}</b><small>المسلسلات</small></div><div class="stat"><b>${list.filter(x=>x.published).length}</b><small>منشور</small></div>`;render()}
function render(query=""){const a=list.filter(x=>x.title.toLowerCase().includes(query.toLowerCase()));document.getElementById("list").innerHTML=a.map(x=>`<div class="admin-row"><img src="${x.poster_url||placeholder(x.title)}"><div class="grow"><b>${esc(x.title)}</b><small>${x.type==="movie"?"فيلم":"مسلسل"} • ${x.year||""}</small></div><button class="mini" onclick="edit('${x.id}')">تعديل</button><button class="mini danger" onclick="del('${x.id}')">حذف</button></div>`).join("")}
async function upload(file,bucket){if(!file)return null;const ext=file.name.split(".").pop();const path=`${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from(bucket).upload(path,file,{upsert:false});if(error){toast(error.message);return null}return sb.storage.from(bucket).getPublicUrl(path).data.publicUrl}
async function save(e){e.preventDefault();const posterFile=poster.files[0],videoFile=video.files[0];let poster_url=editing?.poster_url||null,video_url=editing?.video_url||null;if(posterFile)poster_url=await upload(posterFile,"posters");if(videoFile)video_url=await upload(videoFile,"videos");const payload={title:title.value.trim(),description:description.value.trim(),type:type.value,year:+year.value||null,rating:+rating.value||0,genre:genre.value.trim(),poster_url,video_url,published:true};let id;if(editing){const r=await sb.from("contents").update(payload).eq("id",editing.id).select().single();if(r.error){toast(r.error.message);return}id=r.data.id;await sb.from("episodes").delete().eq("content_id",id)}else{const r=await sb.from("contents").insert(payload).select().single();if(r.error){toast(r.error.message);return}id=r.data.id}if(type.value==="series"){for(const [i,row] of [...document.querySelectorAll(".ep")].entries()){let ev=row.querySelector(".ep-video").files[0];let url=ev?await upload(ev,"videos"):null;await sb.from("episodes").insert({content_id:id,episode_number:i+1,title:row.querySelector(".ep-title").value.trim()||`الحلقة ${i+1}`,video_url:url})}}toast("تم الحفظ");reset();refresh()}
async function edit(id){editing=list.find(x=>x.id===id);if(!editing)return;document.getElementById("formTitle").textContent="تعديل المحتوى";type.value=editing.type;title.value=editing.title;description.value=editing.description||"";year.value=editing.year||"";rating.value=editing.rating||8;genre.value=editing.genre||"";episodeArea.classList.toggle("hidden",editing.type!=="series");episodes.innerHTML="";if(editing.type==="series"){const r=await sb.from("episodes").select("*").eq("content_id",id).order("episode_number");(r.data||[]).forEach(e=>episodeRow(e))}cancel.classList.remove("hidden");scrollTo(0,0)}
async function del(id){if(!confirm("حذف المحتوى؟"))return;await sb.from("episodes").delete().eq("content_id",id);const r=await sb.from("contents").delete().eq("id",id);if(r.error)toast(r.error.message);else{toast("تم الحذف");refresh()}}
function episodeRow(e={}){const d=document.createElement("div");d.className="ep two";d.innerHTML=`<input class="input ep-title" placeholder="اسم الحلقة" value="${esc(e.title||"")}"><input class="input ep-video" type="file" accept="video/*">`;episodes.appendChild(d)}
function reset(){form.reset();editing=null;episodes.innerHTML="";formTitle.textContent="إضافة محتوى";cancel.classList.add("hidden");episodeArea.classList.add("hidden")}
function placeholder(t){return "data:image/svg+xml;charset=UTF-8,"+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="100" height="150"><rect width="100%" height="100%" fill="#182237"/><text x="50%" y="50%" fill="white" font-size="12" text-anchor="middle">${esc(t).slice(0,10)}</text></svg>`)}
function esc(s=""){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function toast(t){const x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2500)}
