const configured=window.SUPABASE_URL && !window.SUPABASE_URL.includes("PASTE_") && window.SUPABASE_ANON_KEY && !window.SUPABASE_ANON_KEY.includes("PASTE_");
let sb=null, items=[], favs=new Set();
if(configured) sb=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
document.addEventListener("DOMContentLoaded",async()=>{bind();if(!configured){demo();return}await load()});
function bind(){document.getElementById("close").onclick=close;document.getElementById("searchBtn").onclick=()=>searchModal();document.querySelectorAll("[data-filter]").forEach(x=>x.onclick=()=>listModal(x.dataset.filter));document.querySelectorAll("[data-nav]").forEach(x=>x.onclick=()=>nav(x.dataset.nav))}
async function load(){const {data,error}=await sb.from("contents").select("*").eq("published",true).order("created_at",{ascending:false});if(error){toast(error.message);demo();return}items=data||[];render();const {data:f}=await sb.from("favorites").select("content_id");favs=new Set((f||[]).map(x=>x.content_id))}
function demo(){items=[{id:1,title:"رحلة منتصف الليل",type:"movie",year:2026,rating:8.7,genre:"إثارة",description:"بيانات تجريبية. اربط Supabase لعرض محتواك الحقيقي.",poster_url:""},{id:2,title:"مدينة الظلال",type:"series",year:2025,rating:8.4,genre:"دراما",description:"مسلسل تجريبي.",poster_url:""}];render()}
function placeholder(t){return "data:image/svg+xml;charset=UTF-8,"+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="500" height="750"><rect width="100%" height="100%" fill="#141c2e"/><text x="50%" y="50%" fill="#fff" font-size="26" text-anchor="middle" font-family="Arial">${esc(t).slice(0,16)}</text></svg>`)}
function img(x){return x.poster_url||placeholder(x.title)}
function esc(s=""){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function card(x){return `<article class="card" onclick="details('${x.id}')"><div class="poster" style="background-image:url('${img(x)}')"><i>${x.type==="movie"?"فيلم":"مسلسل"}</i></div><div class="cb"><b>${esc(x.title)}</b><small>${x.year||""} • ⭐ ${x.rating||"—"}</small></div></article>`}
function render(){const a=[...items];document.getElementById("hero").innerHTML=a[0]?`<div class="hero-bg" style="background-image:url('${img(a[0])}')"></div><div class="hero-content"><small>اختيار اليوم</small><h1>${esc(a[0].title)}</h1><p>${esc(a[0].description||"")}</p><button class="primary" onclick="details('${a[0].id}')">▶ مشاهدة التفاصيل</button></div>`:"";document.getElementById("latest").innerHTML=a.slice(0,5).map(card).join("");document.getElementById("movies").innerHTML=a.filter(x=>x.type==="movie").slice(0,5).map(card).join("");document.getElementById("series").innerHTML=a.filter(x=>x.type==="series").slice(0,5).map(card).join("")}
async function details(id){const x=items.find(y=>String(y.id)===String(id));if(!x)return;let episodes=[];if(x.type==="series"&&configured){const {data}=await sb.from("episodes").select("*").eq("content_id",x.id).order("episode_number");episodes=data||[]}document.getElementById("modalBody").innerHTML=`<div class="detail"><img src="${img(x)}"><div><small>${x.type==="movie"?"فيلم":"مسلسل"}</small><h1>${esc(x.title)}</h1><p class="muted">${x.year||""} • ⭐ ${x.rating||"—"} • ${esc(x.genre||"")}</p><p>${esc(x.description||"")}</p><div class="actions">${x.video_url?`<button class="primary" onclick="play('${esc(x.video_url)}')">▶ تشغيل</button>`:""}<button class="secondary" onclick="favorite('${x.id}')">♥ المفضلة</button></div>${x.type==="series"?`<h3>الحلقات</h3>${episodes.map(e=>`<div class="episode"><span>الحلقة ${e.episode_number}: ${esc(e.title||"")}</span>${e.video_url?`<button class="mini" onclick="play('${esc(e.video_url)}')">▶</button>`:""}</div>`).join("")}`:""}</div></div>`;open()}
function play(url){location.href=url}
async function favorite(id){if(!configured){toast("اربط Supabase لتفعيل المفضلة السحابية");return}const user=(await sb.auth.getUser()).data.user;if(!user){toast("سجّل الدخول أولاً");return}const exists=favs.has(id);if(exists){await sb.from("favorites").delete().eq("content_id",id).eq("user_id",user.id);favs.delete(id)}else{await sb.from("favorites").insert({content_id:id,user_id:user.id});favs.add(id)}toast(exists?"تمت الإزالة":"تمت الإضافة")}
function listModal(filter){const a=filter==="all"?items:items.filter(x=>x.type===filter);document.getElementById("modalBody").innerHTML=`<h2>${filter==="movie"?"الأفلام":filter==="series"?"المسلسلات":"كل المحتوى"}</h2><div class="cards">${a.map(card).join("")}</div>`;open()}
function searchModal(){document.getElementById("modalBody").innerHTML='<h2>البحث</h2><input id="search" class="input" placeholder="اكتب اسم العمل..."><div id="results" class="cards"></div>';open();document.getElementById("search").oninput=e=>{const q=e.target.value.toLowerCase();document.getElementById("results").innerHTML=items.filter(x=>x.title.toLowerCase().includes(q)).map(card).join("")}}
function nav(n){if(n==="search")searchModal();else if(n==="favorites"){const a=items.filter(x=>favs.has(x.id));document.getElementById("modalBody").innerHTML=`<h2>المفضلة</h2><div class="cards">${a.map(card).join("")||"<p class='muted'>لا توجد مفضلات.</p>"}</div>`;open()}else location.href="index.html"}
function open(){document.getElementById("modal").classList.remove("hidden")}function close(){document.getElementById("modal").classList.add("hidden")}function toast(t){const x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2500)}
